### ISSUE TITLE
HTTP Exception in version 0.0.7, pyShelly 0.0.24, Home Assistant 0.91.1

### ISSUE THREAD

**Issue by thecode** [StyraHem/hass#9]
Version 0.0.7, pyShelly 0.0.24, Home Assistant 0.91.1

custom_components/shelly/pyShelly.py (ERROR) - message first occured at 12:35 PM and shows up 43 times

`Error http GET: [Errno 113] Host is unreachableTraceback (most recent call last):
  File "/config/custom_components/shelly/pyShelly.py", line 144, in _http_get
    conn.request("GET", url, None, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable`

**Comment by hakana** [comment]
Can you please change the loglevel for pyShelly to debug. Then you will see the url that fails before the error.

```logger:
  default: info
  logs:
    pyShelly: debug
```

**Comment by thecode** [comment]
OK, with the debug I've found the problem. I have Shelly HT devices in my network, these devices are offline most of the time, they wake up, send data and disconnect from the WIFI.

The last URL in the log before the error was:
2019-04-07 15:28:27 DEBUG (SyncWorker_1) [pyShelly] http://x.y.a.b/status

The IP x.y.a.b is the IP of the Shelly HT.

I think of two possible solutions to this:
1. Detect that the device is Shelly HT and do not try to pull data from it via HTTP
2. Do not log this error

Let me know if additional data is needed.
10x for the development effort.

**Comment by hakana** [comment]
Thanks, that explain. We trying to get some extra information but as you said. I have changed the error login to debug for this.

**Comment by hakana** [comment]
Have you still same problem and are you using latest version?

**Comment by thecode** [comment]
Error still exists.

Error http GET: http://x.y.z.a/status [Errno 113] Host is unreachable Traceback (most recent call last):
  File "/config/custom_components/shelly/pyShelly.py", line 144, in _http_get
    conn.request("GET", url, None, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable

**Comment by hakana** [comment]
Have you changed the ip address in the error message (x.y.z.a)?

I have found the error and it will be fixed in the next release (0.0.11)

**Comment by thecode** [comment]
Yes, I changed the IP :-)

**Comment by hakana** [comment]
That explain the strange IP address ;). I close this issue now.
